apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    uid: prometheus-datasource-uid
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-datasource-uid
    jsonData:
      timeout: 60
      maxLines: 1000